package main

import (
	_ "my-pointlings-be/docs" // docs is generated by Swag CLI, you have to import it.
	"net/http"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title Pointlings API
// @version 1.0
// @description This is a sample server for Pointlings MVP.
// @host localhost:8080
// @BasePath /

func main() {
	r := gin.Default()

	// Swagger endpoint
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Users endpoints
	r.GET("/users/:user_id", getUser)
	r.PATCH("/users/:user_id", updateUserPoints)

	// Pointlings endpoints
	r.GET("/pointlings/:pointling_id", getPointling)
	r.PATCH("/pointlings/:pointling_id/xp", updateXP)
	r.PATCH("/pointlings/:pointling_id", updatePointling)

	// Appearance endpoints
	r.GET("/appearance/:appearance_id", getAppearance)
	r.POST("/appearance", setAppearance)

	// Features and Colors
	r.GET("/features", getFeatures)
	r.GET("/colors", getColors)

	// Wardrobe
	r.GET("/wardrobe/:pointling_id", getWardrobe)
	r.POST("/wardrobe", addWardrobeItem)

	// Accessories and Shop
	r.GET("/accessories", getAccessories)
	r.GET("/shop", getShop)
	r.POST("/purchase", purchaseAccessory)

	// Level-up
	r.POST("/level-up/:pointling_id", levelUp)
	r.POST("/level-up/:pointling_id/choose", chooseLevelUpReward)

	// Debug endpoints
	r.POST("/debug/add-xp", debugAddXP)
	r.POST("/debug/add-to-wardrobe", debugAddToWardrobe)
	r.POST("/debug/add-to-shop", debugAddToShop)

	r.Run(":8080")
}

func getUser(c *gin.Context) {
	// Dummy implementation
	c.JSON(http.StatusOK, gin.H{"message": "getUser"})
}

func updateUserPoints(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{"message": "updateUserPoints"})
}

func getPointling(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{"message": "getPointling"})
}

func updateXP(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{"message": "updateXP"})
}

func updatePointling(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{"message": "updatePointling"})
}

func getAppearance(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{"message": "getAppearance"})
}

func setAppearance(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{"message": "setAppearance"})
}

func getFeatures(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{"message": "getFeatures"})
}

func getColors(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{"message": "getColors"})
}

func getWardrobe(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{"message": "getWardrobe"})
}

func addWardrobeItem(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{"message": "addWardrobeItem"})
}

func getAccessories(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{"message": "getAccessories"})
}

func getShop(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{"message": "getShop"})
}

func purchaseAccessory(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{"message": "purchaseAccessory"})
}

func levelUp(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{"message": "levelUp"})
}

func chooseLevelUpReward(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{"message": "chooseLevelUpReward"})
}

func debugAddXP(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{"message": "debugAddXP"})
}

func debugAddToWardrobe(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{"message": "debugAddToWardrobe"})
}

func debugAddToShop(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{"message": "debugAddToShop"})
}
