// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	models "my-pointlings-be/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// ItemRepository is an autogenerated mock type for the ItemRepository type
type ItemRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: item
func (_m *ItemRepository) Create(item *models.Item) error {
	ret := _m.Called(item)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Item) error); ok {
		r0 = rf(item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: id
func (_m *ItemRepository) GetByID(id int64) (*models.Item, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (*models.Item, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int64) *models.Item); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUnlocksForLevel provides a mock function with given fields: level
func (_m *ItemRepository) GetUnlocksForLevel(level int) ([]*models.Item, error) {
	ret := _m.Called(level)

	if len(ret) == 0 {
		panic("no return value specified for GetUnlocksForLevel")
	}

	var r0 []*models.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]*models.Item, error)); ok {
		return rf(level)
	}
	if rf, ok := ret.Get(0).(func(int) []*models.Item); ok {
		r0 = rf(level)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(level)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: category, rarity, slot
func (_m *ItemRepository) List(category *models.ItemCategory, rarity *models.ItemRarity, slot *models.ItemSlot) ([]*models.Item, error) {
	ret := _m.Called(category, rarity, slot)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.ItemCategory, *models.ItemRarity, *models.ItemSlot) ([]*models.Item, error)); ok {
		return rf(category, rarity, slot)
	}
	if rf, ok := ret.Get(0).(func(*models.ItemCategory, *models.ItemRarity, *models.ItemSlot) []*models.Item); ok {
		r0 = rf(category, rarity, slot)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.ItemCategory, *models.ItemRarity, *models.ItemSlot) error); ok {
		r1 = rf(category, rarity, slot)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewItemRepository creates a new instance of ItemRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewItemRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ItemRepository {
	mock := &ItemRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
