basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: API for managing Pointlings, users, items, and XP system
  title: Pointlings API
  version: "1.0"
paths: {}
produces:
- application/json
schemes:
- http
swagger: "2.0"
tags:
- description: User management endpoints including creation, retrieval, and point
    balance updates
  name: Users
- description: Pointling management including creation, customization, and XP system
  name: Pointlings
- description: Item catalog and inventory management for Pointlings
  name: Items
- description: Experience points system for Pointlings including gaining XP and leveling
    up
  name: XP
